### ISSUE TITLE
`-exe` not working in compiled exe/dll file.

### ISSUE THREAD

**Issue by KookaburraShell** [AZProductions/Kookaburra#125]
## Bug Report

**Current Behavior**
**`-exe`** command not working in compiled exe/dll files.

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/71338293/132100284-2c00d903-6b17-4a70-8386-0c1e14188674.png)

**Comment by AZProductions** [comment]
Fixed, used **`Process.GetCurrentProcess().MainModule.FileName`** instead of ***`System.Reflection.Assembly.GetEntryAssembly().Location`***. 

Fix will be implemented in Version **0.8.5**.
