### ISSUE TITLE
`clear` command writes an additional line at the end.

### ISSUE THREAD

**Issue by KookaburraShell** [AZProductions/Kookaburra#126]
The `clear` or `cls` writes an additional line at the end for ANSI compatible terminal/console. We should implement a *full clear system*. Example:
- `clear` or `cls` uses [System.Console.Clear](https://docs.microsoft.com/en-us/dotnet/api/system.console.clear?view=net-5.0).
- **`fclear` or `fcls` or `fullclear` uses [Kookaburra.SDK.Format.Clear](https://github.com/AZProductions/KookaburraSDK/blob/8106c75849f3ab4203b16f714bc3bfe46b517ace/Kookaburra.SDK/Format.cs#L152-L159).**

**Comment by AZProductions** [comment]
Feature will be implemented in Version **0.8.5**.
