### ISSUE TITLE
0.7.X features? 📣

### ISSUE THREAD

**Issue by KookaburraShell** [AZProductions/Kookaburra#16]
Let us know if you want us to add more features! **Just comment the idea(s)**

**Comment by KookaburraShell** [comment]
- Networking
- API support
- Sound and Image support

**Comment by AZProductions** [comment]
> * Sound and Image support

I guess we can use spectre.console.

**Comment by KookaburraShell** [comment]
> > * Sound and Image support
> 
> _I guess we can use **spectre.console.**_

_Sound support will only be for **windows**._

**Comment by KookaburraShell** [comment]
Add more info to _Syntax error_ page.
Example: `Syntax error at line 7. _Print "hello world"_ should be **lowercase**.`

**Comment by AZProductions** [comment]
Intuitive command feedback.
`
Command ‘helpp’ not found. Here are similar commands.

Command ‘help’.
`

**Comment by KookaburraShell** [comment]
System commands like:
```
Shutdown
Restart
Volume up/down
```

**Comment by AZProductions** [comment]
> ```
> Shutdown
> Restart
> Volume up/down
> ```

I guess it will work using cmd on Windows.

**Comment by KookaburraShell** [comment]
These features and one big surprise feature will be added in 0.6.0.

**Comment by AZProductions** [comment]
Some features aren't in the 0.6.0 final release, these will be carried on to the 0.7.0 release system.
