### ISSUE TITLE
Networking! 🌐

### ISSUE THREAD

**Issue by KookaburraShell** [AZProductions/Kookaburra#21]
> - Networking

_Originally posted by @KookaburraShell in https://github.com/AZProductions/Kookaburra/issues/16#issuecomment-855238544_

**Comment by KookaburraShell** [comment]
- [ ] import net
- [ ] binding?

**Comment by AZProductions** [comment]
- **HTTPS Web client?**
- TCP
- _UCP?_

**Comment by KookaburraShell** [comment]
All feature requests are now on Jira.
