### ISSUE TITLE
Security fix. 🛑

### ISSUE THREAD

**Issue by KookaburraShell** [AZProductions/Kookaburra#8]
Create server with url manager. In case of a breach, redirect users to a backup server.

**Comment by KookaburraShell** [comment]
> redirect users to a backup server.
Doesn't work with system.net.filedownload

**Comment by AZProductions** [comment]
Fixed with backup link.https://github.com/AZProductions/Kookaburra/blob/c0f30ee4cf9d0da07e7edd33716178b16bc7e882/packages/update/loc.txt#L1
