### ISSUE TITLE
New `startup_ui`!

### ISSUE THREAD

**Issue by AZProductions** [AZProductions/Kookaburra#80]
Were creating a new 'UNIX' style startup UI. Mock-ups coming soon! 

We need a good system for making our logo into **ACII** or **Unicode**.

## Failed methods
- Manual ACII conversion.
- ImageSharp rendering.

**Comment by AZProductions** [comment]
Our first test was a to abstract.
```c#
using Spectre.Console;

AnsiConsole.MarkupLine("                    ");
AnsiConsole.MarkupLine("[orange1]                 (( [/]");
AnsiConsole.MarkupLine("          [springgreen3_1]/[/][springgreen2]/[/][lightseagreen]/[/][cornflowerblue]/[/][slateblue3_1]/[/][blueviolet]/[/][orange1]#[/][darkorange]([/]  ");
AnsiConsole.MarkupLine("   [green3_1]***[/]   [springgreen3_1]/[/][springgreen2]/[/][lightseagreen]/[/][cornflowerblue]/[/][slateblue3_1]/[/][blueviolet]/[/][blue]/[/][blue3]/[/][darkblue]*[/]  ");
AnsiConsole.MarkupLine("   [green3_1]**[/][springgreen2]***[/][springgreen3]*[/][springgreen3_1]/[/][springgreen2]/[/][lightseagreen]/[/][cornflowerblue]/[/][slateblue3_1]/[/][blueviolet]/[/][blue]/[/][blue3]/[/][navyblue]*[/]  ");
AnsiConsole.MarkupLine("    [springgreen2]***[/][springgreen3]**[/][deepskyblue3]*[/][deepskyblue4_2]*[/][springgreen3_1]/[/][springgreen2]/[/][lightseagreen]/[/][cornflowerblue]/[/][slateblue3_1]/[/][blueviolet]/[/][blue]/[/][navyblue]*[/]   ");
AnsiConsole.MarkupLine("                    ");
```
![Example](https://user-images.githubusercontent.com/66299945/127305975-0255f2ed-7fd1-4e33-801e-a20db1948aac.png)

**Comment by KookaburraShell** [comment]
We've done some test using **spectre.console.imagesharp**, which looked _less detailed_.

**Comment by KookaburraShell** [comment]
We need a good system for making our logo into **ACII** or **Unicode**.

**Comment by AZProductions** [comment]
Test 3: Using https://stackoverflow.com/a/33715138

<details open> 
            <summary>Geeks classes</summary> 

![image](https://user-images.githubusercontent.com/66299945/129725903-14edfb87-8fde-4cc1-bfc3-6be10c70f09b.png)

</details>

**Comment by AZProductions** [comment]
We can revisit this idea in the future, we currently don't need a *UI refresh* unless there's a way to display high quality images.
